version: '3'
services:
  app:
    image: pyapp:1.1
    ports:
      - "5000"
  nginx:
    image: nginx
    depends_on: 
      - app
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro