nodes = [
    { :hostname => 'node1-master', :ip => '10.245.1.122', :memory => 2048, :cpu => 1, :boxname => 'spox/ubuntu-arm', :hdd => '30GB' },
    { :hostname => 'node2-master', :ip => '10.245.1.123', :memory => 2048, :cpu => 1, :boxname => 'spox/ubuntu-arm', :hdd => '30GB' }
    { :hostname => 'node3-worker', :ip => '10.245.1.125', :memory => 1536, :cpu => 1, :boxname => 'spox/ubuntu-arm', :hdd => '20GB' },
    { :hostname => 'node4-worker', :ip => '10.245.1.126', :memory => 1536, :cpu => 1, :boxname => 'spox/ubuntu-arm', :hdd => '20GB' },
]

Vagrant.configure("2") do |config|
    nodes.each do |node|
        config.vm.box_check_update = false
        config.disksize.size = node[:hdd]
        config.vm.define node[:hostname] do |nodeconfig|
            nodeconfig.vm.box = node[:boxname]
            nodeconfig.vm.hostname = node[:hostname]
            nodeconfig.vm.network :private_network, ip: node[:ip]
            nodeconfig.vm.provider :vmware_desktop do |vmware|
                vmware.gui = true
                vmware.cpus = node[:cpu]
                vmware.memory = node[:memory]
                vmware.vmx["ethernet0.virtualdev"] = "vmxnet3"
                vmware.ssh_info_public = true
                vmware.linked_clone = false
           end
        end
    end
end

