version: '3'
services:
  postgres_master:
    container_name: postgres_master
    image: custom_postgres:1.4
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data      
      - ./init-script/ini2.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data-slave:/var/lib/postgresql/data-slave
      - ./init-script:/etc/postgresql/init-script
      - ./init-script/config/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./init.sh:/etc/postgresql/init-script/init.sh
    ports:
      - "5432:5432"
    env_file:
      - ../.env

  postgres_slave:
    container_name: postgres_slave
    image: custom_postgres:1.4
    restart: always
    volumes:
      - ./data-slave:/var/lib/postgresql/data
      - ./init-script/config/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./init-script/config/postgres.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5434:5432"
    env_file:
      - ../.env
  generator:
    image: go-generator:1.0.2
    build:
      context: ../goGenerator/gen
    env_file:
      - .env

  pg_pool:
    container_name: pg_pool
    image: bitnami/pgpool:4.5.1
    restart: always
    ports:
      - "5433:5432"
    depends_on:
      - postgres_master
      - postgres_slave
    environment:
      - PGPOOL_BACKEND_NODES=0:postgres_master:5432:4:primary:ALWAYS_PRIMARY,1:postgres_slave:5432:6:replica
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=postgres
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=admin
      - PGPOOL_ENABLE_STATEMENT_LOAD_BALANCING=yes
      - PGPOOL_NUM_INIT_CHILDREN=10
      - PGPOOL_MAX_POOL=1
      - PGPOOL_SR_CHECK_USER=postgres
      - PGPOOL_SR_CHECK_PASSWORD=postgres