version: '3'
services:
  postgres:
    image: custom_postgres:1.4
    container_name: pg_master
    ports:
      - "5432:5432"
    env_file: 
      - .env
    volumes:
      - ./data/backup:/backup
      - ./ini2.sql:/docker-entrypoint-initdb.d/init.sql
      - ./scripts:/scripts
#  generator:
#    image: go-generator
#    build:
#      context: ./goGenerator/gen
#    depends_on:
#      - postgres
#    env_file:
#      - .env