version: '3'
services:
  postgres:
    image: custom_postgres:1.4
    container_name: pg_master
    ports:
      - "5432:5432"
    env_file: 
      - .env
    volumes:
      - ./data/backup:/backup
      - ./ini2.sql:/docker-entrypoint-initdb.d/ini2.sql
