- hosts: vm1
  become: true
  tasks:
    - name: clean dirs
      shell: |
        rm -r /home/vagrant/shared
#        todo сделать проверку через баш, что есть такие директории stage
        rm -r /home/vagrant/stage*
    - name: Удалить пользователя developer
      user:
        name: developer
        state: absent

    - name: Удалить пользователя manager
      user:
        name: manager
        state: absent

    - name: Удалить группу projects
      group:
        name: projects
        state: absent