- hosts: all
  become: true
  tasks:
    - name: add new group - projects
      group:
        name: projects

    - name: add developer user
      user:
        name: developer
        comment: "Developer User"
        password: "{{ 'developer' | password_hash('sha512') }}"
        group: projects
        append: yes

    - name: add manager user
      user:
        name: manager
        comment: 'Manager user'
        password: "{{ 'manager' | password_hash('sha512') }}"
        group: projects
        append: yes

    - name: create folders and files
      become: false
      command: bash /home/vagrant/folders.sh
    
    - name: change dir owner
      shell: |
        chown -R manager /home/vagrant/shared/project

    - name: set group to new files in projects
      shell: |
        chmod g+s /home/vagrant/shared/project

    - name: change dir group owner
      shell: |
        chown -R :projects /home/vagrant/shared/project

    - name: change project dir permissions
      shell: |
        chmod -R ug+rw /home/vagrant/shared/project
        chmod -R o-rx /home/vagrant/shared/project